from .deconvnetmodel import *
from .deeplab_v2 import *
from .deeplab_v2_multiscale import *
from .deeplab_vggmodel import *
from .dilatedmodel import *
from .ducmodel import *
from .fcnmodel import *
from .gcnmodel import *
from .linknetmodel import *
from .segnetmodel import *
from .tiramisu import *
from .tiramisu_nobias import *